Bitaqat/Bitaqat/urls.py
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('org/', include('Club.urls')),
    path('guest/', include('Fan.urls')),
    path('', include('django.contrib.auth.urls'))
    # path("debug/", include(debug_toolbar.urls)),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Bitaqat/Fan/urls.py
from django.urls import path
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
app_name = 'Fan'

urlpatterns = [
    path('homepage/', views.renderHomepage, name="renderHomepage"),
    path('Marketplace/', views.renderMarketplace, name="renderMarketplace"),
    path('Buy/<str:event_id>/', views.buyTicket, name='buyTicket'),
    path('Myinventory/', views.renderInventory, name='renderInventory'),
    path("Mykeys/", views.renderKeys, name="Mykeys"),
    path("verification/<str:token_id>/", views.generate_qr_code, name="verf"),
    path("feedback/",views.giveFeedback,name="feedback"),
     path("receive/", views.ReceiverContractEvents, name="receive")
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bitaqat/authentication/urls.py
from django.urls import path, include
from .views import landing_page, login_my_users, create_accounts, password_reset_complete
from django.contrib.auth import views as auth_views
app_name = 'authentication'

urlpatterns = [
    path('', landing_page, name="landingPage"),
    path('login/', login_my_users, name="loginmyUsers"),
    path('register/', create_accounts, name='createAccounts'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='authentication/resetpassword.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/emailsentmsg.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='authentication/resetform.html'), name='password_reset_confirm'),
    path('reset/done/',
         password_reset_complete, name='password_reset_complete')
]

Bitaqat/authentication/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.core.validators import EmailValidator


class myUsers(AbstractUser):
    email = models.EmailField(max_length=254)
    username = models.CharField(max_length=50,unique=True,primary_key=True)

Bitaqat/authentication/views.py
from django.shortcuts import render, reverse
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.hashers import make_password
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from eth_account import Account
import secrets
from Fan.SmartContract import sendFromMother
from Club.models import myClub as Club
from .models import myUsers
from Fan.models import myFan
import environ
env = environ.Env()
environ.Env.read_env()

def create_wallet():
    """
    Create a cryptocurrency wallet.

    :return: A private key and its corresponding address.
    """
    priv = secrets.token_hex(32)
    private_key = "0x" + priv
    acct = Account.from_key(private_key)
    return private_key, acct.address

def login_my_users(request):
    """
    Log in the user if the request method is POST and the user is authenticated.

    :param request: The HTTP request object.
    :return: HTTP response.
    """
    if request.method == "POST":
        username_client = request.POST.get('username')
        password_client = request.POST.get('pswrd')
        user = authenticate(request, username=username_client, password=password_client)

        if user is not None:
            user_pk = user.pk
            club_model_check = Club.objects.filter(pk=user_pk).exists()
            fan_model_check = myFan.objects.filter(pk=user_pk).exists()

            if club_model_check:
                login(request, user)
                return HttpResponseRedirect(reverse("Club:renderHomepage"))
            elif fan_model_check:
                login(request, user)
                return HttpResponseRedirect(reverse("Fan:renderHomepage"))

        return render(request, 'authentication/Login.html', {'error_msg': True})
    else:
        return render(request, 'authentication/Login.html')

def create_accounts(request):
    """
    Create a user account and save it in the database.

    :param request: The HTTP request object.
    :return: HTTP response.
    """
    try:
        if request.method == "POST":
            email_client = request.POST.get('emailadd')
            username_client = request.POST.get('username')
            password_client = request.POST.get('pswrd')
            password_client_hashed = make_password(password_client)

            try:
                validate_email(email_client)
            except ValidationError:
                error_msg = "Invalid email address"
                return render(request, "authentication/Registration.html", {"error_msg_valid": error_msg})
            # Create two wallets for each user: one for NFTs and one for gas fees
            wallet = create_wallet()  # NFT wallet
            gasWallet = create_wallet()  # Auth Wallet
            public_address = wallet[1]
            private_address = wallet[0]
            user = myUsers.objects.create(
                username=username_client, email=email_client, password=password_client_hashed)
            account = myFan(user=user, NFT_Wallet_public_key=public_address,
                            NFT_Wallet_private_key=private_address, Gas_Wallet_public_key=gasWallet[1], Gas_Wallet_private_key=gasWallet[0])
            # Sending funds for the gas fees
            sendFromMother(gasWallet[1],5)
            user.save()
            account.save()

            return render(request, "authentication/Login.html")
        else:
            return render(request, "authentication/Registration.html")
    except IntegrityError as e:
        error_msg = ''
        if str(e) == "UNIQUE constraint failed: auth_user.email":
            error_msg = "An account with this email address already exists"
            return render(request, "authentication/Registration.html", {"error_msg_email": error_msg})
        else:
            error_msg = "An account with this username already exists"
            return render(request, "authentication/Registration.html", {"error_msg_username": error_msg})

def landing_page(request):
    """
    Render the landing page.

    :param request: The HTTP request object.
    :return: HTTP response.
    """
    return render(request, 'authentication/landingPage.html')

def password_reset_complete(request):
    """
    Render the password reset completion page.

    :param request: The HTTP request object.
    :return: HTTP response.
    """
    return render(request, 'authentication/resetdone.html')

Bitaqat/authentication/templates/authentication/Login.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;1,200;1,300;1,400&display=swap"
        rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Login</title>
</head>

<body>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');

        body {

            font-size: 16px;
            background-color: #06182c !important;
            color: #fff !important;
            margin: 25px;
        }

        .login-container {
            height: 100vh;
            width: 100%;

        }

        .text-color {
            font-family: 'Russo One', sans-serif !important;
            color: #fff !important
        }

        .login-form {
            margin: auto;
            width: 370px;
            padding: 15px;
            max-width: 100%;
        }

        .login-form .form-control {
            font-size: 19px;
            min-height: 48px;
            font-weight: 500;
        }

        .login-form a {
            text-decoration: none;
            color: #666;
        }

        .login-form a:hover {
            color: #723dbe;
        }

        .forgot-link {
            font-size: 15px;
        }

        .form-control:focus {
            border-color: #723dbe;
            box-shadow: 0 0 0 0.2rem rgba(114, 61, 190, .25);
        }


        .btn-color {
            margin-top: 10px;
            background-color: #0052ff !important;
            border-color: rgb(0, 0, 0);
            color: #fff !important;
            font-family: 'Russo One', sans-serif !important;
        }

        .form-check-label {
            font-size: 17px;
        }

        .img-placer {
            margin-top: 40px;
        }
    </style>



    <div class="login-container d-flex align-items-center justify-content-center ">
        <form class="login-form text-center" onsubmit="return verify_password()"
            action="{% url 'authentication:loginmyUsers' %}" method="post">
            {% csrf_token %}
            <h1 class="mb-5 font-weight-light text-uppercase text-color">Login</h1>

            <div class="form-group">
                <input type="text" name="username" class="form-control rounded-pill form-control-lg" id="username"
                    placeholder="Enter username">
            </div>
            <div class="form-group">
                <input type="password" name="pswrd" class="form-control rounded-pill form-control-lg"
                    id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-row">
                {% if error_msg %}
                <small id="loginerror" class="" style=" color: red ; font-size: medium; ">Username and Password
                    dosen't match</small>
                </small>
                {% endif %}
                {% if error_msg2 %}
                <small id="loginerror" class="" style=" color: red ; font-size: medium; ">You don't have an Organizer
                    Account , please create one</small>
                </small>
                {% endif %}
                {% if error_msg3 %}
                <small id="loginerror" class="" style=" color: red ; font-size: medium; ">You don't have an Attandee
                    Account , please create one</small>
                </small>
                {% endif %}
                {% if error_msg4 %}
                <small id="loginerror" class="" style=" color: red ; font-size: medium; ">please choose account
                    type</small>
                </small>
                {% endif %}

            </div>
            <button type="submit" class="btn btn-color btn-block rounded-pill btn-lg ">Login</button>
            <p class="mt-3 font-weight-normal">Don't have an account <a href="/register"><strong>Register
                        Now</strong></a>
            </p>
            <img src="{% static 'images/Iconlogin.svg' %}" class="img-placer" height="200px">
    </div>









    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Bitaqat/authentication/templates/authentication/Registration.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Registration.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>CreateAccount</title>
</head>

<style>
    @import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');

    body {

        font-size: 16px;
        background-color: #06182c !important;
        color: #fff !important;
        margin: 25px;
    }

    .login-container {
        height: 100vh;
        width: 100%;

    }

    .text-color {
        font-family: 'Russo One', sans-serif !important;
        color: #fff !important
    }

    .login-form {
        margin: auto;
        width: 370px;
        padding: 15px;
        max-width: 100%;
    }

    .login-form .form-control {
        font-size: 19px;
        min-height: 48px;
        font-weight: 500;
    }

    .login-form a {
        text-decoration: none;
        color: #666;
    }

    .login-form a:hover {
        color: #723dbe;
    }

    .forgot-link {
        font-size: 15px;
    }

    .form-control:focus {
        border-color: #723dbe;
        box-shadow: 0 0 0 0.2rem rgba(114, 61, 190, .25);
    }


    .btn-color {
        margin-top: 10px;
        background-color: #0052ff !important;
        border-color: rgb(0, 0, 0);
        color: #fff !important;
        font-family: 'Russo One', sans-serif !important;
    }

    .form-check-label {
        font-size: 17px;
    }

    .img-placer {
        margin-top: 40px;
    }
</style>

<body>




    <div class="login-container d-flex align-items-center justify-content-center ">
        <form class="login-form text-center" onsubmit="return verify_password()"
            action="{% url 'authentication:createAccounts' %}" method="post">
            {% csrf_token %}
            <h1 class="mb-5 font-weight-light text-uppercase text-color">Sign up</h1>

            <div class="form-group">
                <input type="email" name="emailadd"
                    class="form-control rounded-pill form-control-lg form-control rounded-pill form-control-lg rounded-pill form-control rounded-pill form-control-lg-lg"
                    id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                {% if error_msg_email %}
                <small id="emailerror" class="" style=" color: red ; font-size: medium; ">An Account with this email
                    address already exists.
                </small>
                {% endif %}
                {% if error_msg_valid %}
                <small id="emailerror" class="" style=" color: red ; font-size: medium; ">Invalid email address
                </small>
                {% endif %}
            </div>
            <div class="form-group">
                <input type="text" name="username" class="form-control rounded-pill form-control-lg" id="username"
                    placeholder="Enter username">
                {% if error_msg_username %}
                <small id="usererror" class="" style=" color: red ; font-size: medium; ">An Account with this
                    username already exists.
                </small>
                {% endif %}
            </div>

            <div class="form-group">
                <input type="password" name="pswrd" class="form-control rounded-pill form-control-lg"
                    id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group">
                <input type="password" class="form-control rounded-pill form-control-lg" id="passwordverification"
                    placeholder="Confirm password">
            </div>
            <!-- 
            <div class="form-group">
                <input class="form-check-input" type="radio" value="Event Organizer" id="EO" name="res"
                    onclick="return show_organisers_more_inputs()">
                <label class="form-check-label" for="EO">
                    Event Organizer
                </label>
            </div>

            <div class="form-groupe">
                <input class="form-check-input" type="radio" value="Event Attandee" id="EA" name="res"
                    onclick="return remove_ele()" checked>
                <label class="form-check-label" for="EA">
                    Event Attandee
                </label>
            </div> -->


            <button type="submit" class="btn btn-block rounded-pill btn-lg btn-color">Register</button>
            <p class="mt-3 font-weight-normal">Already have an Account? <a href="/login"><strong>Login</strong></a>
            </p>
            <img src="{% static 'images\RegistrationIcon.svg'%}" class="img-placer" height="200px">
    </div>






    <script>
        let confirmed_password = document.querySelector("#passwordverification");
        let real_password = document.querySelector("#exampleInputPassword1");
        function verify_password() {
            if (confirmed_password.value != real_password.value) {
                alert("Password dosen't match")
                window.location.href = "/signup"
            }

        }



        // function show_organisers_more_inputs() {


        //     let added_inputs_location = document.getElementById("inputCity")
        //     let html = `
        //         <div class="form-group my-3">
        //             <input type="text" name="organisation" class="form-control rounded-pill form-control-lg" id="Coname" placeholder="Enter Company name">
        //         </div>
        //     `
        //     added_inputs_location.insertAdjacentHTML('afterend', html)


        //     return null
        // }
        // function remove_ele() {
        //     let ele = document.getElementById("Coname")
        //     ele.remove()
        // }

    </script>




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Bitaqat/authentication/templates/authentication/emailsentmsg.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;1,200;1,300;1,400&display=swap"
        rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>reset password</title>
</head>

<body>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');

        body {

            font-size: 16px;
            background-color: #06182c !important;
            color: #fff !important;
            margin: 25px;
        }

        .login-container {
            height: 100vh;
            width: 100%;

        }

        .text-color {
            font-family: 'Russo One', sans-serif !important;
            color: #fff !important
        }

        .login-form {
            margin: auto;
            width: 370px;
            padding: 15px;
            max-width: 100%;
        }

        .login-form .form-control {
            font-size: 19px;
            min-height: 48px;
            font-weight: 500;
        }

        .login-form a {
            text-decoration: none;
            color: #666;
        }

        .login-form a:hover {
            color: #723dbe;
        }

        .forgot-link {
            font-size: 15px;
        }

        .form-control:focus {
            border-color: #723dbe;
            box-shadow: 0 0 0 0.2rem rgba(114, 61, 190, .25);
        }


        .btn-color {
            margin-top: 10px;
            background-color: #0052ff !important;
            border-color: rgb(0, 0, 0);
            color: #fff !important;
            font-family: 'Russo One', sans-serif !important;
        }

        .form-check-label {
            font-size: 17px;
        }

        .img-placer {
            margin-top: 40px;
        }
    </style>



    <div class="login-container d-flex align-items-center justify-content-center ">
        <form class="login-form text-center" method="post">
            {% csrf_token %}
            <h1 class="mb-5 font-weight-light text-uppercase text-color">Check your inbox</h1>

            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>

            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check
                your spam folder.</p>
            <img src="{% static 'images/mail.svg' %}" class="img-placer" height="200px">
    </div>









    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

Bitaqat/authentication/templates/authentication/resetdone.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,500;0,600;1,200;1,300;1,400&display=swap"
        rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>reset password</title>
</head>

<body>

    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900');

        body {

            font-size: 16px;
            background-color: #06182c !important;
            color: #fff !important;
            margin: 25px;
        }

        .login-container {
            height: 100vh;
            width: 100%;

        }

        .text-color {
            font-family: 'Russo One', sans-serif !important;
            color: #fff !important
        }

        .login-form {
            margin: auto;
            width: 370px;
            padding: 15px;
            max-width: 100%;
        }

        .login-form .form-control {
            font-size: 19px;
            min-height: 48px;
            font-weight: 500;
        }

        .login-form a {
            text-decoration: none;
            color: #666;
        }

        .login-form a:hover {
            color: #723dbe;
        }

        .forgot-link {
            font-size: 15px;
        }

        .form-control:focus {
            border-color: #723dbe;
            box-shadow: 0 0 0 0.2rem rgba(114, 61, 190, .25);
        }


        .btn-color {
            margin-top: 10px;
            background-color: #0052ff !important;
            border-color: rgb(0, 0, 0);
            color: #fff !important;
            font-family: 'Russo One', sans-serif !important;
        }

        .form-check-label {
            font-size: 17px;
        }

        .img-placer {
            margin-top: 40px;
        }
    </style>



    <div class="login-container d-flex align-items-center justify-content-center ">
        <form class="login-form text-center" method="post">
            {% csrf_token %}
            <h1 class="mb-5 font-weight-light text-uppercase text-color">Reset password complete</h1>

            <p>Your password has been set. You may go ahead and <a href="/login/">log in now</a>.</p>

            <img src="{% static 'images/mail.svg' %}" class="img-placer" height="200px">
    </div>









    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>